### ISSUE TITLE
Configuration loss if using callbacks

### ISSUE THREAD

**Issue by responseinformationsdesign** [YolfTypo3/SavCharts#2] opened 2020-01-21 12:28 UTC
Example:

```
<item key="scales">
    <item key="xAxes">
        <item key="0">
            <item key="ticks">
                <item key="min" value="0" />
                <item key="max" value="marker#maxX" />
                <item key="fontSize" value="15" />
                <item key="fontFamily" value="Segoe Alt W00 Light" />
                <item key="fontColor" value="rgb(88, 97, 104)" />
            </item>
        </item>
    </item>
</item>
```
correctly generates:

```
options:{"scales":{"xAxes":[{"ticks":{"min":0,"max":70,"fontSize":15,"fontFamily":"Segoe Alt W00 Light","fontColor":"rgb(88, 97, 104)"}
```

If a callback is added
 

```
<item key="scales">
    <item key="xAxes">
        <item key="0">
            <item key="ticks">
                <item key="min" value="0" />
                <item key="max" value="marker#maxX" />
                <item key="fontSize" value="15" />
                <item key="fontFamily" value="Segoe Alt W00 Light" />
                <item key="fontColor" value="rgb(88, 97, 104)" />
                <callback key="callback">
                    <!--
                    function(value, index, values) {
                        return value + ' %';
                    }
                    -->
                </callback>
            </item>
        </item>
    </item>
</item>
```

 the callback works as expected but the rest of the configuration of he parent key is totally lost:
 
```
options:{"scales":{"xAxes":[{"ticks":{"callback":
    function(value, index, values) {
      return value + ' %';
    }
}
```

**Comment by YolfTypo3** [comment] 2020-02-07 08:25
I cannot reproduce this bug. I close this issue. Please reopen it with more details if you still have this problem.

**Closed as completed by YolfTypo3** 2020-02-07 08:25 UTC
